### ISSUE TITLE
Problem Instantiating A Group from Dict with Members

### ISSUE THREAD

**Issue by ruberVulpes** [seratch/python-slack-scim#5]
Hi, I've been trying this code to create a SCIM Group from existing Slack Users 
```python
import logging
import os

import slack_scim
from slack.web.classes.interactions import IDNamePair
from slack_scim import Group, GroupMember

logging.basicConfig(level=logging.DEBUG)
client = slack_scim.SCIMClient(token=os.environ["SLACK_ADMIN_TOKEN"])

users = [IDNamePair('<id>', 'William'), IDNamePair('<id>', 'Peter')]
members = [GroupMember.from_dict({'value': user.id}) for user in users]
display_name = 'My Test Group'
new_group = Group.from_dict({'displayName': display_name, 'members': members})
```
and I've been getting this exception trace back from trying to create the group from dict 

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1.3\plugins\python\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/William Fox/AppData/Roaming/JetBrains/PyCharm2020.2/scratches/slack-scim-tests.py", line 14, in <module>
    new_group = Group.from_dict({'displayName': display_name, 'members': members})
  File "C:\Users\William Fox\PycharmProjects\slack-channel-restrictor\venv\lib\site-packages\slack_scim\v1\group.py", line 107, in from_dict
    members = from_union([lambda x: from_list(Member.from_dict, x), from_none], obj.get("members"))
  File "C:\Users\William Fox\PycharmProjects\slack-channel-restrictor\venv\lib\site-packages\slack_scim\v1\group.py", line 31, in from_union
    assert False
AssertionError
```

However if I instead make the Group with just the `displayName` and then update members later I'm able to create the group successfully 
```python
new_group = Group.from_dict({'displayName': display_name})
new_group.members = members
result = client.create_group(new_group)
```

I'm unsure if this is a bug or my usage is wrong

`Python Version 3.7.7`

**Comment by seratch** [comment]
@ruberVulpes This library doesn't rely on `slackclient` PyPI package and doesn't provide any supports for the types under `slack.web.classes` at this point. Please use plain dict objects instead of `IDNamePair` class.

**Comment by ruberVulpes** [comment]
I removed the `IDNamePair` namedtuple 
```python
```

**Comment by ruberVulpes** [comment]
I removed the `IDNamePair` namedtuple and have the following code, but I still get the stack trace in the original post
```python
import logging
import os

import slack_scim
from slack_scim import Group, GroupMember

logging.basicConfig(level=logging.DEBUG)
client = slack_scim.SCIMClient(token=os.environ["SLACK_ADMIN_TOKEN"])

user_ids = ['<id>', '<id>']
members = [GroupMember.from_dict({'value': user_id}) for user_id in user_ids]
display_name = 'My Test Group'
new_group = Group.from_dict({'displayName': display_name, 'members': members})
```

**Comment by jlumbroso** [comment]
@ruberVulpes Does this also produce a stack trace:
```python
import logging
import os

import slack_scim

logging.basicConfig(level=logging.DEBUG)
client = slack_scim.SCIMClient(token=os.environ["SLACK_ADMIN_TOKEN"])

display_name = "my-test-group"

new_group: slack_scim.Group = slack_scim.Group.from_dict({"displayName": display_name})

new_group.members = [slack_scim.GroupMember(value=id) for id in user_ids]

creation_result: slack_scim.Group = client.create_group(new_group)
if not creation_result:
    search_result: slack_scim.Groups = client.search_groups(filter=f"displayName eq {display_name}", count=1)
    creation_result: slack_scim.Group = search_result.resources[0]
group_id = creation_result.id

print(group_id)
```

**Comment by ruberVulpes** [comment]
@jlumbroso I have to do 
```python
new_group.members = [slack_scim.GroupMember(value=id, display=None) for id in user_ids]
```
to avoid an exception on the `GroupMember` init but the code works fine for me

I think I would prefer to assign the group members when I instantiate the group object but doing it in a list comp later isn't terrible imo
